FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code



COPY requirements requirements/
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . /code/

# configure awscli
# get env vars from docker-compose
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION

# print env vars to check

RUN MKDIR ~/.aws
RUN echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
RUN echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials


# note: if you don't want to run collectstatic on every deploy you can remove this line.
RUN python manage.py collectstatic --noinput --settings=searing_ai.settings_do
