version: "3.9"

services:
  db:
    image: postgres
    # persist data beyond lifetime of container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DJANGO_DATABASE_NAME}
      - POSTGRES_USER=${DJANGO_DATABASE_USER}
      - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
    env_file:
      - ./.env

  web:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  celery:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: celery -A searing_ai worker -l INFO --beat
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: