default_context:
  _pegasus_version: '2022.9'
  author_name: Darin
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: Learn shit. Real fast.
  domain_name: localhost:8000
  email: ghb8745@gmail.com
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  project_name: Searing.ai
  project_slug: searing_ai
  stripe_payment_mode: checkout
  subscription_billing_model: default
  use_api_keys: y
  use_docker: n
  use_impersonation: n
  use_sentry: n
  use_subscriptions: n
  use_teams: n
  use_translations: y
  use_wagtail: n
