/* tslint:disable */
/* eslint-disable */
/**
 * Searing.ai
 * Learn shit. Real fast.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
} from './Document';

/**
 * 
 * @export
 * @interface PaginatedDocumentList
 */
export interface PaginatedDocumentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDocumentList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDocumentList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDocumentList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Document>}
     * @memberof PaginatedDocumentList
     */
    results?: Array<Document>;
}

/**
 * Check if a given object implements the PaginatedDocumentList interface.
 */
export function instanceOfPaginatedDocumentList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedDocumentListFromJSON(json: any): PaginatedDocumentList {
    return PaginatedDocumentListFromJSONTyped(json, false);
}

export function PaginatedDocumentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDocumentList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(DocumentFromJSON)),
    };
}

export function PaginatedDocumentListToJSON(value?: PaginatedDocumentList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(DocumentToJSON)),
    };
}

