/* tslint:disable */
/* eslint-disable */
/**
 * Searing.ai
 * Learn shit. Real fast.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedDocument
 */
export interface PatchedDocument {
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedDocument
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedDocument
     */
    file?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedDocument
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedDocument
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedDocument
     */
    readonly user?: string;
}

/**
 * Check if a given object implements the PatchedDocument interface.
 */
export function instanceOfPatchedDocument(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedDocumentFromJSON(json: any): PatchedDocument {
    return PatchedDocumentFromJSONTyped(json, false);
}

export function PatchedDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'file': !exists(json, 'file') ? undefined : json['file'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function PatchedDocumentToJSON(value?: PatchedDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'file': value.file,
    };
}

