/* tslint:disable */
/* eslint-disable */
/**
 * Searing.ai
 * Learn shit. Real fast.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedSummary
 */
export interface PatchedSummary {
    /**
     * 
     * @type {number}
     * @memberof PatchedSummary
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSummary
     */
    readonly document?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSummary
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSummary
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSummary
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the PatchedSummary interface.
 */
export function instanceOfPatchedSummary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedSummaryFromJSON(json: any): PatchedSummary {
    return PatchedSummaryFromJSONTyped(json, false);
}

export function PatchedSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'document': !exists(json, 'document') ? undefined : json['document'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function PatchedSummaryToJSON(value?: PatchedSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}

