/* tslint:disable */
/* eslint-disable */
/**
 * Searing.ai
 * Learn shit. Real fast.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Summary
 */
export interface Summary {
    /**
     * 
     * @type {number}
     * @memberof Summary
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Summary
     */
    readonly document: string | null;
    /**
     * 
     * @type {string}
     * @memberof Summary
     */
    content?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Summary
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Summary
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the Summary interface.
 */
export function instanceOfSummary(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "document" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function SummaryFromJSON(json: any): Summary {
    return SummaryFromJSONTyped(json, false);
}

export function SummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Summary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'document': json['document'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SummaryToJSON(value?: Summary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}

