
databases:
- engine: PG
  name: searing-ai-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
- cluster_name: searing-ai-redis
  engine: REDIS
  name: searing-ai-redis
  production: true
  version: "6"
name: searing-ai
region: nyc
services:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${searing-ai-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: searing_ai.settings_do
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'bSjIADcyCAMJaUyrepchzgAUXHplrKFvovCyYrXr'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${searing-ai-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: user/searing-ai
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: searing-ai-web
  routes:
  - path: /
  run_command: gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 0 --worker-tmp-dir /dev/shm searing_ai.wsgi:application
workers:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${searing-ai-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: searing_ai.settings_do
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'bSjIADcyCAMJaUyrepchzgAUXHplrKFvovCyYrXr'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${searing-ai-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: user/searing-ai
  instance_count: 1
  instance_size_slug: basic-xs
  name: searing-ai-celery
  run_command: celery -A searing_ai worker -l INFO --pool=gevent
