
databases:
- engine: PG
  name: searing-ai-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
- cluster_name: searing-ai-redis
  engine: REDIS
  name: searing-ai-redis
  production: true
  version: "6"
name: searing-ai
region: nyc
services:
- dockerfile_path: Dockerfile.web
  envs:
  - key: aws_access_key_id
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:1LajAqlWAYdY1tIkNxoFmbCrHhTWr1ET:zLG833G84Y1JwjE0qxWAnNA7pnXnJuuNJ97AmtCfm+JCK/aK]
  - key: aws_secret_access_key
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:kq4MnlEkrnmELdi4C4gitmS+qHWRgrH7:PgfSKx9TqQS3zSijzbRT+ySui5HaIbw79Emmw+2pTqVadjbQnb1F3/2kU9ihB6OWWxhsfi6+8n0=]
  - key: aws_reigon
    scope: RUN_AND_BUILD_TIME
    value: us-west-2
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:j4THHkStNZn76yflg3YKjeE0nnPs2N3X:w5hrv03tYrPnZgGsUZ6LugqYMy6yhEOkALidCkKu9KJRJRZ1hV520QHySzxk+17oa2sqwyNH8BkWVgtpvBZwZgyTEDdInMnrTlkT2d5a2j4b2UVdHlr/jDyQRmQqntXND5GfepyJ1qs=]
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    type: plain
    value: searing_ai.settings_do
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:KW3LspOKZffbeIrT3tIuJ4Zgcp2HutVw:nBF9UntvlwoT8h+gKbIrjPe6d2pcr0EePctRzAoFVtj1WbG9rxPqGfV+X1G6JF9z5leCNGBOIhG8ihToU0jF26Dp]
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:3zW2vo0bZwo+gLRGdlwjRX83kpyjr/Hk:lS6UTzx8xzrlLhmGjPELtBKgXIA2A2OBojpDxbSBK0/lENGZKvhTTNHnJj7dYzrf3Ta79WvzrLnt3wDhAmb3/iZrthOnJ283BFeN59g2x8Y6d0HfLHfpw7e0Jliq7O/6gPTJg1Vdvw/cWMSx055/mA+GyLsAmFAVGxY+Lw==]
  github:
    branch: master
    deploy_on_push: true
    repo: darinkishore/searing_ai
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: searing-ai-web
  routes:
  - path: /
  run_command: gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 0 --worker-tmp-dir /dev/shm searing_ai.wsgi:application
workers:
- dockerfile_path: Dockerfile.web
  envs:
  - key: aws_access_key_id
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:1LajAqlWAYdY1tIkNxoFmbCrHhTWr1ET:zLG833G84Y1JwjE0qxWAnNA7pnXnJuuNJ97AmtCfm+JCK/aK]
  - key: aws_secret_access_key
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:kq4MnlEkrnmELdi4C4gitmS+qHWRgrH7:PgfSKx9TqQS3zSijzbRT+ySui5HaIbw79Emmw+2pTqVadjbQnb1F3/2kU9ihB6OWWxhsfi6+8n0=]
  - key: aws_reigon
    scope: RUN_AND_BUILD_TIME
    value: us-west-2
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:j4THHkStNZn76yflg3YKjeE0nnPs2N3X:w5hrv03tYrPnZgGsUZ6LugqYMy6yhEOkALidCkKu9KJRJRZ1hV520QHySzxk+17oa2sqwyNH8BkWVgtpvBZwZgyTEDdInMnrTlkT2d5a2j4b2UVdHlr/jDyQRmQqntXND5GfepyJ1qs=]
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: searing_ai.settings_do
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:KW3LspOKZffbeIrT3tIuJ4Zgcp2HutVw:nBF9UntvlwoT8h+gKbIrjPe6d2pcr0EePctRzAoFVtj1WbG9rxPqGfV+X1G6JF9z5leCNGBOIhG8ihToU0jF26Dp]
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:3zW2vo0bZwo+gLRGdlwjRX83kpyjr/Hk:lS6UTzx8xzrlLhmGjPELtBKgXIA2A2OBojpDxbSBK0/lENGZKvhTTNHnJj7dYzrf3Ta79WvzrLnt3wDhAmb3/iZrthOnJ283BFeN59g2x8Y6d0HfLHfpw7e0Jliq7O/6gPTJg1Vdvw/cWMSx055/mA+GyLsAmFAVGxY+Lw==]
  github:
    branch: master
    deploy_on_push: true
    repo: darinkishore/searing_ai
  instance_count: 1
  instance_size_slug: basic-xs
  name: searing-ai-celery
  run_command: celery -A searing_ai worker -l INFO --pool=gevent
