# Generated by Django 3.2.14 on 2022-09-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220914_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='<django.db.models.fields.related.ForeignKey>/documents/'),
        ),
    ]
