# Generated by Django 4.1.1 on 2022-09-15 22:56

import apps.data.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, null=True, storage=apps.data.storage_backends.PrivateMediaStorage, upload_to='documents/'),
        ),
    ]
