# Generated by Django 4.1.1 on 2022-09-16 00:16

import apps.data.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, storage=apps.data.storage_backends.PrivateMediaStorage, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
