# Generated by Django 4.1.1 on 2022-09-17 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_document_file_alter_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(default=None)),
                ('answer', models.TextField(default=None)),
                ('document', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='data.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
