# Generated by Django 4.1.1 on 2022-09-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_question_alter_summary_content_delete_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='job_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.JSONField(default=dict),
        ),
    ]
