# Generated by Django 4.1.1 on 2022-09-22 23:22

import apps.data.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_document_ocr_text_alter_document_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.FileField(blank=True, default=None, null=True, storage=apps.data.storage_backends.PrivateMediaStorage, upload_to='documents/'),
        ),
    ]
