# Generated by Django 4.1.1 on 2022-10-12 00:42

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0010_alter_summary_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions',
                                    to='data.document'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='document',
            field=annoying.fields.AutoOneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE,
                                                    primary_key=True, related_name='summary', serialize=False,
                                                    to='data.document'),
        ),
    ]
